version: "3"
services:
 frontend:
  build:
   context: ./frontend
  container_name: react-frontend
  ports:
   - "80:80"
 backend:
  build:
   context: ./backend
  container_name: flask-backend
  ports:
   - "5000:5000"
  depends_on:
   db:
    condition: service_healthy
  links:
   - "db"
 db:
  # Reference the docker-compose-db.yml file here
  extends:
   file: docker-compose-db.yml
   service: db
