version: "3"

services:
 db:
  image: postgres:13.3
  container_name: postgres-db-container
  restart: always
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: mypassword
   POSTGRES_DB: postgres
  ports:
   - "5432:5432"
  healthcheck:
   test: ["CMD-SHELL", "pg_isready -U postgres"]
   interval: 10s
   timeout: 5s
   retries: 5
